### ISSUE TITLE
Relay /helpop commands

### ISSUE THREAD

**Issue by amalon** [dhghf/matrix-appservice-minecraft#15]
The EssentialsX plugin has a /helpop command for communicating with an op. It'd be cool if that could optionally be relayed through to matrix. perhaps to a different matrix room, or as a direct message to a specific matrix user (so that replies can be sent back only to that player)?

**Comment by dhghf** [comment]
For this to happen we would need to develop a [puppeted](https://matrix.org/docs/guides/types-of-bridging#simple-puppeted-bridge) bridge or allow multiple bridges from one server at once with configurations of what gets sent to each one. Either way this will get postponed for a later version
